### ISSUE TITLE
Model lipsync and blinking not working

### ISSUE THREAD

**Issue by benjaminlim00** [inworld-ai/inworld-web-sdk#43]
https://github.com/inworld-ai/inworld-web-sdk/tree/main/examples/generate_token
The example generate_token server crashes upon request. Here is the error code I am facing:

![Screenshot 2023-08-09 at 11 46 24 AM](https://github.com/inworld-ai/inworld-web-sdk/assets/36101433/021bd178-67fb-4fba-ac12-6eae35b7596e)
![Screenshot 2023-08-09 at 11 46 29 AM](https://github.com/inworld-ai/inworld-web-sdk/assets/36101433/1caf78df-1dfc-48f8-bfd8-827a6ff0a504)

**Comment by benjaminlim00** [comment]
I managed to resolve this issue by pulling the latest changes. However there were import errors to be fixed, such as the wrong import path of ```src/app/components/Skeleton/Skeleton.tsx```

**Comment by benjaminlim00** [comment]
It seems that the src/app/components/3dAvatar/Lipsync.tsx file is not working as it should,
<img width="671" alt="Screenshot 2023-08-09 at 1 58 33 PM" src="https://github.com/inworld-ai/inworld-web-sdk/assets/36101433/9338f71a-fb1a-43f4-81ff-83bf890a5a03">
there is no morphTargetInfluences key on the skinnedMesh object, resulting in a runtime error. 
<img width="578" alt="Screenshot 2023-08-09 at 1 59 26 PM" src="https://github.com/inworld-ai/inworld-web-sdk/assets/36101433/4b9875ea-9e1e-48cb-b7bc-26c791b4ef4c">

**Comment by benjaminlim00** [comment]
There is a similar error in the `src/app/components/3dAvatar/Model.tsx` file:
<img width="769" alt="Screenshot 2023-08-09 at 2 00 10 PM" src="https://github.com/inworld-ai/inworld-web-sdk/assets/36101433/07329e83-d12b-4c3c-9c8c-70b8da835ba5">
```targetNames``` is not a key that exists on the `mesh.userDat`a object.

**Comment by tshashkova** [comment]
@benjaminlim00 
Lipsync example was fixed
You can check

**Comment by benjaminlim00** [comment]
Thank you @tshashkova , I have tested it and it is working fine 😄
